<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '123 App Street, Apt. 4B' => '',
    'About' => 'О нас',
    'About Us - SimpleMapp' => 'О нас - SimpleMapp',
    'App Categories &raquo;' => 'Категории приложений &raquo;',
    'Applications' => 'Приложения',
    'At **SimpleMapp**, we are proud to create simple yet powerful Android applications,' => 'В **SimpleMapp** мы гордимся созданием простых, но мощных Android-приложений,',
    'Community and Support' => 'Сообщество и поддержка',
    'Contact' => 'Контакты',
    'Contact Form' => 'Контактная форма',
    'Contact Us' => 'Связаться с нами',
    'Details' => 'Подробнее',
    'Digital Land' => '',
    'Discover our products, made with care for you!' => 'Откройте для себя наши продукты, созданные с заботой о вас!',
    'Do you have questions about our apps, suggestions for new features, or need support? Feel free to fill out the form below, and we will get back to you as soon as possible.' => '',
    'Download on Google Play' => 'Скачать в Google Play',
    'Ease of Use' => 'Простота использования',
    'Email' => 'Электронная почта',
    'For Education and Life' => 'Для образования и жизни',
    'For general inquiries, feel free to use the contact form.' => '',
    'Go Back' => 'Назад',
    'Go to Apps' => 'Перейти к приложениям',
    'Go to Our Apps &raquo;' => 'Перейти к нашим приложениям &raquo;',
    'Home' => 'Главная',
    'Innovative Solutions Ltd.' => '',
    'Join SimpleMapp!' => 'Присоединяйтесь к SimpleMapp!',
    'Learn About SimpleMapp' => 'Узнать о SimpleMapp',
    'Meet the Team &raquo;' => 'Познакомиться с командой &raquo;',
    'Message' => 'Сообщение',
    'Name' => 'Имя',
    'Our Contacts' => 'Наши контакты',
    'Our Philosophy &raquo;' => 'Наша философия &raquo;',
    'Our Products' => 'Наши продукты',
    'Our Products - SimpleMapp' => 'Наши продукты - SimpleMapp',
    'Our Products: Apps for Everyone.' => 'Наши продукты: Приложения для всех.',
    'Our Team' => 'Наша команда',
    'Our Team: Passion for Android and Innovation.' => 'Наша команда: Страсть к Android и инновациям.',
    'Our Vision' => 'Наше видение',
    'Our Vision: Simplicity in Every Solution.' => 'Наше видение: Простота в каждом решении.',
    'Our vision of simplicity' => 'Наше видение простоты',
    'Page Under Development' => 'Страница в разработке',
    'Products' => 'Продукты',
    'Ready to simplify your world?' => 'Готовы упростить свой мир?',
    'SimpleMapp — Simplifying the world with mobile apps' => 'SimpleMapp — Упрощаем мир с помощью мобильных приложений',
    'Stay tuned for our updates! We are constantly working on new applications and improving existing ones.' => 'Следите за нашими обновлениями! Мы постоянно работаем над новыми приложениями и улучшаем существующие.',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Support and Contact &raquo;' => 'Поддержка и контакты &raquo;',
    'Team at work' => 'Команда в работе',
    'Tech City, Zip 98765' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо за обращение. Мы ответим вам как можно скорее.',
    'This page is currently under development and will be available soon.' => 'Эта страница в настоящее время находится в разработке и будет доступна скоро.',
    'Verification Code' => 'Код проверки',
    'View Our Apps' => 'Посмотреть наши приложения',
    'We are always happy to help you with any questions or suggestions. Here is our contact information:' => 'Мы всегда рады помочь вам с любыми вопросами или предложениями. Вот наши контактные данные:',
    'We are working hard to bring you new and useful features. Please check back later!' => 'Мы усердно работаем над тем, чтобы предоставить вам новые и полезные функции. Пожалуйста, загляните позже!',
    'Welcome to SimpleMapp!' => 'Добро пожаловать в SimpleMapp!',
    'What\'s New in SimpleMapp?' => 'Что нового в SimpleMapp?',
    'that help you in education, daily life organization, and development.' => 'которые помогают вам в образовании, организации повседневной жизни и развитии.',
];
