---
deployment:
  tasks:
    - export DEPLOYPATH=/home/egewe258/public_html/
    - /usr/bin/rsync -avz --delete --exclude='vendor' --exclude='runtime' --exclude='.git' --exclude='.idea' --exclude='node_modules' ./ $DEPLOYPATH
