<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '123 App Street, Apt. 4B' => '',
    'About' => 'Про нас',
    'About Us - SimpleMapp' => 'Про нас - SimpleMapp',
    'App Categories &raquo;' => 'Категорії додатків &raquo;',
    'Applications' => 'Додатки',
    'At **SimpleMapp**, we are proud to create simple yet powerful Android applications,' => 'У **SimpleMapp** ми пишаємося створенням простих, але потужних Android-додатків,',
    'Community and Support' => 'Спільнота та підтримка',
    'Contact' => 'Контакти',
    'Contact Form' => 'Форма зворотного звʼязку',
    'Contact Us' => 'Звʼязатися з нами',
    'Details' => 'Детальніше',
    'Digital Land' => 'Цифровий світ',
    'Discover our products, made with care for you!' => 'Відкрийте для себе наші продукти, створені з турботою про вас!',
    'Do you have questions about our apps, suggestions for new features, or need support? Feel free to fill out the form below, and we will get back to you as soon as possible.' => '',
    'Download on Google Play' => 'Завантажити на Google Play',
    'Ease of Use' => 'Простота використання',
    'Email' => 'Електронна пошта',
    'For Education and Life' => 'Для освіти та життя',
    'For general inquiries, feel free to use the contact form.' => '',
    'Go Back' => 'Назад',
    'Go to Apps' => 'Перейти до додатків',
    'Go to Our Apps &raquo;' => 'Перейти до наших додатків &raquo;',
    'Home' => 'Головна',
    'Innovative Solutions Ltd.' => '',
    'Join SimpleMapp!' => 'Приєднуйтесь до SimpleMapp!',
    'Learn About SimpleMapp' => 'Дізнатися про SimpleMapp',
    'Meet the Team &raquo;' => 'Зустрітися з командою &raquo;',
    'Message' => 'Повідомлення',
    'Name' => 'Імʼя',
    'Our Contacts' => 'Наші контакти',
    'Our Philosophy &raquo;' => 'Наша філософія &raquo;',
    'Our Products' => 'Наші продукти',
    'Our Products - SimpleMapp' => 'Наші продукти - SimpleMapp',
    'Our Products: Apps for Everyone.' => 'Наші продукти: Додатки для всіх.',
    'Our Team' => 'Наша команда',
    'Our Team: Passion for Android and Innovation.' => 'Наша команда: Пристрасть до Android та інновацій.',
    'Our Vision' => 'Наше бачення',
    'Our Vision: Simplicity in Every Solution.' => 'Наше бачення: Простота в кожному рішенні.',
    'Our vision of simplicity' => 'Наше бачення простоти',
    'Page Under Development' => 'Сторінка в розробці',
    'Products' => 'Продукти',
    'Ready to simplify your world?' => 'Готові спростити свій світ?',
    'SimpleMapp — Simplifying the world with mobile apps' => 'SimpleMapp — Спрощуємо світ за допомогою мобільних додатків',
    'Stay tuned for our updates! We are constantly working on new applications and improving existing ones.' => 'Слідкуйте за нашими оновленнями! Ми постійно працюємо над новими додатками та покращуємо існуючі.',
    'Subject' => 'Тема',
    'Submit' => 'Надіслати',
    'Support and Contact &raquo;' => 'Підтримка та контакти &raquo;',
    'Team at work' => 'Команда за роботою',
    'Tech City, Zip 98765' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Дякуємо за звернення. Ми відповімо вам якомога швидше.',
    'This page is currently under development and will be available soon.' => 'Ця сторінка наразі знаходиться в розробці і буде доступна незабаром.',
    'Verification Code' => 'Код перевірки',
    'View Our Apps' => 'Переглянути наші додатки',
    'We are always happy to help you with any questions or suggestions. Here is our contact information:' => '',
    'We are working hard to bring you new and useful features. Please check back later!' => 'Ми наполегливо працюємо над тим, щоб запропонувати вам нові та корисні функції. Будь ласка, поверніться пізніше!',
    'Welcome to SimpleMapp!' => 'Ласкаво просимо до SimpleMapp!',
    'What\'s New in SimpleMapp?' => 'Що нового в SimpleMapp?',
    'that help you in education, daily life organization, and development.' => 'що допомагають вам в освіті, організації повсякденного життя та розвитку.',
    'Website under development' => 'Сайт в розробці',
];
